[package]
name = "gqlitecli"
version = "0.3.0"
edition = "2021"
license = "MIT"
description = "Command Line Interface tool for GQLite"
readme = "README.md"
homepage = "https://gqlite.org"
repository = "https://gitlab.com/gqlite/gqlite"

[[bin]]
name = "gqlite"
path = "src/main.rs"

[dependencies]
gqlitedb = { version = "0.3.0", path = "../.." }
rustyline = "15"
standard_paths = "2.1.0"
tabled = "0.17"

# [[bin]]
# path= "src/main.rs"
# name = "gqlite"
