[workspace]
resolver = "2"
members = ["gqliterb", "gqlitedb", "graphcore"]

[workspace.package]
version = "0.6.3"
edition = "2021"
license = "MIT"
homepage = "https://gqlite.org"
repository = "https://gitlab.com/gqlite/gqlite"

[workspace.dependencies]
graphcore = { version = "0.2.3", path = "graphcore" }
gqlitedb = { version = "0.6.3", path = "gqlitedb" }

askama = { version = "0.14" }
ccutils = { version = "0.4" }
itertools = "0.14"
serde = "1"
thiserror = "2"
uuid = { version = "1", features = ["v4"] }
