# Prevent two pipelines to run for a merge request and for wip branches
workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_COMMIT_REF_NAME =~ /wip\/.*/
      when: always
    - if: $CI_COMMIT_REF_NAME =~ /wip\/.*/
      when: never
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: never
    - if: $CI_COMMIT_BRANCH

stages: # List of stages for jobs, and their order of execution
  - precheck
  - build
  - test
  - benchmark
  - postcheck

include:
  - project: "cyloncore/cc_ci_templates"
    file: "/scripts-ci.yml"
    ref: "stable"

.build_template: &build_definition
  script:
    - mkdir build
    - pushd build
    - cmake .. -DCMAKE_INSTALL_PREFIX=../inst -DGQLITE_TESTS_OUTPUT_JUNIT=ON -DGQLITE_TESTS_DISABLE_RUST_TESTS=ON -DCMAKE_BUILD_TYPE=release
    - make -j8 install
    - popd
  artifacts:
    paths:
      - build/
      - inst/
    expire_in: 1day

.test_template: &test_definition
  script:
    - pwd
    - ls
    # Export installation
    - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:`pwd`/inst/lib
    - export RUBYLIB=$RUBYLIB:`pwd`/inst/lib/ruby
    - export PYTHON3_VERSION=`python3 -c "import sys; print(str(sys.version_info.major) + '.' + str(sys.version_info.minor), end='');"`
    - export PYTHONPATH=$PYTHONPATH:`pwd`/inst/lib/python$PYTHON3_VERSION/dist-packages
    - echo $RUBYLIB
    - echo $PYTHONPATH
    - pushd build
    - make test
    - popd
    - cargo nextest run
  artifacts:
    when: always
    expire_in: 30 days
    paths:
      - build/Testing
    reports:
      junit:
        - build/Testing/junit/*.xml
        - build/Testing/junit/*/*.xml
        - target/nextest/default/junit.xml

.benchmark_template: &benchmark_definition
  before_script:
    # Prepare SSH key
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa

    # Add known hosts (GitLab.com or your Git host)
    - ssh-keyscan gitlab.com >> ~/.ssh/known_hosts

    - echo "🧬 Clone $TARGET_REPO"
    - git clone $TARGET_REPO results_repo
    - pushd results_repo
    - git config user.email "ci-bot@auksys.org"
    - git config user.name "CI Bot"
    - popd
  after_script:
    - echo "📤 Push results to $TARGET_REPO"
    - pushd results_repo
    - git pull --rebase
    - git push
    - popd

precheck:
  stage: precheck
  extends: .cc_all_checks
  variables:
    CC_CI_REF_BRANCH: "dev/1"

check-default-features:
  stage: precheck
  script:
    - grep -q 'default = \["redb", "capi", "sqlite"\]' crates/gqlitedb/Cargo.toml

# Extra-tests
clippy:
  stage: postcheck
  image: cyloncore/ci:debian
  script:
    - cargo clippy -- -D warnings
  needs:
    - job: "debian:build"
      artifacts: true

doc:
  stage: postcheck
  image: cyloncore/ci:debian
  script:
    - cargo doc --no-deps
  needs:
    - job: "debian:build"
      artifacts: true

semver:
  stage: postcheck
  image: cyloncore/ci:debian
  script:
    - cargo semver-checks --exclude gqliterb --exclude gqlitepy --exclude gqlparser
  needs:
    - job: "debian:build"
      artifacts: true

coverage:
  stage: postcheck
  image: cyloncore/ci:debian
  script:
    - cargo llvm-cov
  needs:
    - job: "debian:build"
      artifacts: true

dists:
  stage: postcheck
  image: cyloncore/ci:debian
  script:
    - yet bindings/ruby/build_gem
    - yet bindings/python/make_sdist
  needs:
    - job: "debian:build"
      artifacts: true
  artifacts:
    when: always
    expire_in: 30 days
    paths:
      - bindings/ruby/pkg/gqlite-*.gem
      - bindings/python/gqlitepy/wheels/gqlitedb-*.tar.gz

test_ruby_gem:
  stage: postcheck
  image: cyloncore/ci:ruby
  script:
    - gem install bindings/ruby/pkg/gqlite-*.gem
    - rspec tests/rb/gqlite-rspec.rb
  needs:
    - job: "dists"
      artifacts: true

test_python_src_wheels:
  stage: postcheck
  image: python:3.9
  script:
    - pip3 install bindings/python/gqlitepy/wheels/gqlitedb-*.tar.gz
    - python3 tests/py/python-unittest.py
  needs:
    - job: "dists"
      artifacts: true

benchmarks_iai:
  stage: benchmark
  image: cyloncore/ci:debian
  variables:
    TARGET_REPO: git@gitlab.com:GQLite/benchmark-results.git
    TARGET_SUB_DIR: $CI_COMMIT_SHA/pokec_iai
    TARGET_DIR: results_repo/$TARGET_SUB_DIR
  dependencies: []
  script:
    - mkdir -p ${TARGET_DIR}

    - echo "🚀 Run 'iai' benchmarks..."

    # Needed to work around valgrind opening too many file descriptors
    - export VALGRIND_LIB="/tmp/valgrind"
    - export VALGRIND_OPTS="--track-fds=no"
    - ulimit -n 1024
    - export PATH=`pwd`/scripts/workaround/iai_callgrind/:$PATH
    - cargo bench -p gqlitedb --bench pokec_iai -- --save-summary=json --home=pokec_iai | tee ${TARGET_DIR}/${CI_PIPELINE_ID}.log

    - echo "💾 Export results to $TARGET_REPO"
    - bash scripts/move_pokec_iai_files.sh ${TARGET_DIR} ${CI_PIPELINE_ID}
    - ruby scripts/iai_json_to_csv.rb ${TARGET_DIR}/${CI_PIPELINE_ID}.*.json > ${TARGET_DIR}/${CI_PIPELINE_ID}.csv

    - echo "📝 Commit results to $TARGET_REPO"
    - pushd results_repo
    - git add ${TARGET_SUB_DIR}/${CI_PIPELINE_ID}.log ${TARGET_SUB_DIR}/${CI_PIPELINE_ID}.*.json ${TARGET_SUB_DIR}/${CI_PIPELINE_ID}.csv
    - git commit -m "Add iai-callgrind benchmark results for commit $CI_COMMIT_SHA pipeline $CI_PIPELINE_ID"
    - popd
  <<: *benchmark_definition

benchmarks_divan:
  stage: benchmark
  image: cyloncore/ci:debian-arm64
  variables:
    TMP_BENCH_FILE: bench_output.tmp
    TARGET_REPO: git@gitlab.com:GQLite/benchmark-results.git
    TARGET_SUB_DIR: $CI_COMMIT_SHA/pokec_divan
    TARGET_DIR: results_repo/$TARGET_SUB_DIR
  script:
    - echo "🚀 Run 'divan' benchmarks..."
    - cargo bench -p gqlitedb --bench pokec_divan | tee $TMP_BENCH_FILE

    - echo "💾 Export results to $TARGET_REPO"
    - mkdir -p ${TARGET_DIR}
    - cat $TMP_BENCH_FILE | ruby scripts/export_divan.rb "${TARGET_DIR}/$CI_PIPELINE_ID"

    - echo "📝 Commit results to $TARGET_REPO"
    - pushd results_repo
    - git add ${TARGET_SUB_DIR}/${CI_PIPELINE_ID}.txt ${TARGET_SUB_DIR}/${CI_PIPELINE_ID}.csv
    - git commit -m "Add divan benchmark results for commit $CI_COMMIT_SHA pipeline $CI_PIPELINE_ID"
    - popd

  needs:
    - job: precheck
  tags:
    - bench
  dependencies: []
  <<: *benchmark_definition

# Debian
debian:build:
  image: cyloncore/ci:debian
  stage: build
  <<: *build_definition

debian:test: # This job runs in the test stage.
  image: cyloncore/ci:debian
  stage: test # It only starts when the job in the build stage completes successfully.
  needs:
    - job: "debian:build"
      artifacts: true
  <<: *test_definition

# Ubuntu
ubuntu:build:
  image: cyloncore/ci:ubuntu-noble
  stage: build
  <<: *build_definition

ubuntu:test: # This job runs in the test stage.
  image: cyloncore/ci:ubuntu-noble
  stage: test # It only starts when the job in the build stage completes successfully.
  needs:
    - job: "ubuntu:build"
      artifacts: true
  <<: *test_definition

# Fedora
fedora:build:
  image: cyloncore/ci:fedora
  stage: build
  <<: *build_definition

fedora:test: # This job runs in the test stage.
  image: cyloncore/ci:fedora
  stage: test # It only starts when the job in the build stage completes successfully.
  needs:
    - job: "fedora:build"
      artifacts: true
  <<: *test_definition
