.before_script_template_deb: &before_script_deb
  - echo "Installing packages..."
  - apt-get -qq update && apt-get -qq install cmake g++ libsqlite3-dev ruby-dev ruby-ffi python3-dev python3-cffi python3-pytest xz
  - gem install rspec cucumber rspec_junit_formatter

.before_script_template_yum: &before_script_yum
  - echo "Installing packages..."
  - yum install -yy cmake g++ sqlite-devel sqlite-devel ruby-devel rubygem-ffi redhat-rpm-config python3-cffi python3-devel python3-cffi python3-pytest xz
  - gem install rspec cucumber rspec_junit_formatter

.before_script_template_yum_rocky: &before_script_yum_rocky
  - echo "Installing packages..."
  - yum install -yy cmake g++ sqlite-devel sqlite-devel ruby-devel  redhat-rpm-config python3-cffi python3-devel python3-cffi python3-pytest xz
  - gem install rspec cucumber rspec_junit_formatter ffi

stages:          # List of stages for jobs, and their order of execution
  - build
  - test

.build_template: &build_definition
  script:
    - mkdir build
    - pushd build
    - cmake .. -DCMAKE_INSTALL_PREFIX=../inst -DGQLITE_TESTS_OUTPUT_JUNIT=ON
    - make -j8 install
    - popd
  artifacts:
    paths:
      - build/
      - inst/
    expire_in: 1day

.test_template: &test_definition
  script:
    - pwd
    - ls
    - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:`pwd`/inst/lib
    - export RUBYLIB=$RUBYLIB:`pwd`/inst/lib/ruby
    - export PYTHON3_VERSION=`python3 -c "import sys; print(str(sys.version_info.major) + '.' + str(sys.version_info.minor), end='');"`
    - export PYTHONPATH=$PYTHONPATH:`pwd`/inst/lib/python$PYTHON3_VERSION/dist-packages
    - echo $RUBYLIB
    - echo $PYTHONPATH
    - pushd build
    - make test
    - popd
  artifacts:
    when: always
    expire_in: 30 days
    paths:
      - build/Testing
    reports:
      junit: build/Testing/junit/*.xml

# Debian
debian:build:
  image: debian
  stage: build
  before_script:
    - *before_script_deb
  <<: *build_definition

debian:test:   # This job runs in the test stage.
  image: debian
  stage: test    # It only starts when the job in the build stage completes successfully.
  before_script:
    - *before_script_deb
  needs:
    - job: "debian:build"
      artifacts: true
  <<: *test_definition

# Ubuntu
ubuntu:build:
  image: ubuntu
  stage: build
  before_script:
    - *before_script_deb
  <<: *build_definition

ubuntu:test:   # This job runs in the test stage.
  image: ubuntu
  stage: test    # It only starts when the job in the build stage completes successfully.
  before_script:
    - *before_script_deb
  needs:
    - job: "ubuntu:build"
      artifacts: true
  <<: *test_definition

# Fedora
fedora:build:
  image: fedora
  stage: build
  before_script:
    - *before_script_yum
  <<: *build_definition

fedora:test:   # This job runs in the test stage.
  image: fedora
  stage: test    # It only starts when the job in the build stage completes successfully.
  before_script:
    - *before_script_yum
  needs:
    - job: "fedora:build"
      artifacts: true
  <<: *test_definition

# rockylinux
# standard sqlite is too old
# rockylinux:build:
#   image: rockylinux:9
#   stage: build
#   before_script:
#     - *before_script_yum_rocky
#   <<: *build_definition

# rockylinux:test:   # This job runs in the test stage.
#   image: rockylinux:9
#   stage: test    # It only starts when the job in the build stage completes successfully.
#   before_script:
#     - *before_script_yum_rocky
#   needs:
#     - job: "rockylinux:build"
#       artifacts: true
#   <<: *test_definition