[workspace]
resolver = "2"
members = [
  "bindings/python/gqlitepy",
  "bindings/ruby/gqliterb",
  "bindings/rune/gqliterune",
  "crates/*",
]

[workspace.package]
version = "0.6.0"
edition = "2021"
license = "MIT"
homepage = "https://gqlite.org"
repository = "https://gitlab.com/gqlite/gqlite"

[workspace.dependencies]
# versions have to be specified with path: https://github.com/rust-lang/cargo/issues/11133
graphcore = { version = "0.1.0", path = "crates/graphcore" }
gqb = { version = "0.1.0", path = "crates/gqb" }
gqlitedb = { version = "0.6.0", path = "crates/gqlitedb" }

askama = { version = "0.14" }
itertools = "0.14"
serde = "1"
thiserror = "2"
uuid = { version = "1", features = ["v4"] }

[patch.crates-io]
# rusqlite = { git = "https://github.com/Spxg/rusqlite.git", branch = "wasm-demo", features = [] }
