[workspace]
resolver = "2"
members = ["bindings/python/gqlitepy", "bindings/ruby/gqliterb", "crates/*"]

[workspace.package]
version = "0.5.2"
edition = "2021"
license = "MIT"
homepage = "https://gqlite.org"
repository = "https://gitlab.com/gqlite/gqlite"

[workspace.dependencies]
gqlitedb = { version = "0.5.2", path = "crates/gqlitedb" }

# versions have to be specified with path: https://github.com/rust-lang/cargo/issues/11133
[patch.crates-io]
# rusqlite = { git = "https://github.com/Spxg/rusqlite.git", branch = "wasm-demo", features = [] }
