tag-name = "gqlitedb-v{{version}}"
pre-release-commit-message = "Release gqlite crates version {{version}}.\n\nThis release version {{version}} of gqlitedb, gqlitecli, gqlitebrowser and gqliterune.\n\nIssues: None"
