WHITESPACE     = _{ " " | "\t" | "\n" }
COMMENT        = _{ ("//" ~ (!"\n" ~ ANY)*) | ("/*" ~ (!"*/" ~ ANY)* ~ "*/") }
ident          = @{ ASCII_ALPHA ~ (ASCII_ALPHANUMERIC | "_")* }
parameter_name = @{ (ASCII_ALPHANUMERIC | "_")* }
char           =  {
    !("'" | "\\") ~ ANY
  | "\\" ~ ("\"" | "\\" | "/" | "b" | "f" | "n" | "r" | "t")
  | "\\" ~ ("u" ~ ASCII_HEX_DIGIT{4})
}
nothing_ident  = @{ "###"+ }

// Query
query = _{ SOI ~ statement* ~ ";"? ~ EOI }

nothing = { nothing_ident? }

// fragments

labels       = { ":" ~ label_expression }
pattern      = { ident? ~ labels? ~ map? }
node_pattern = { "(" ~ pattern ~ ")" }

directed_edge_pattern   = { (")-[" ~ pattern ~ "]->(") | (nothing ~ ")-->(") }
reversed_edge_pattern   = { (")<-[" ~ pattern ~ "]-(") | (nothing ~ ")<--(") }
undirected_edge_pattern = { (")-[" ~ pattern ~ "]-(") | (")<-[" ~ pattern ~ "]->(") | (nothing ~ ")--(") }
edge_pattern            = { "(" ~ pattern ~ ((directed_edge_pattern | reversed_edge_pattern | undirected_edge_pattern) ~ pattern)+ ~ ")" }

path_pattern = { ident ~ "=" ~ "(" ~ pattern ~ (directed_edge_pattern | reversed_edge_pattern | undirected_edge_pattern) ~ pattern ~ ")" }

node_or_edge_pattern         = _{ edge_pattern | node_pattern }
node_or_edge_or_path_pattern = _{ edge_pattern | node_pattern | path_pattern }

// Modifiers

order_by_kw = @{ "ORDER" ~ WHITESPACE+ ~ "BY" ~ !ASCII_ALPHA }
limit_kw    = @{ "LIMIT" ~ !ASCII_ALPHA }
skip_kw     = @{ "SKIP" ~ !ASCII_ALPHA }

limit                    = { limit_kw ~ expression }
order_by                 = { order_by_kw ~ (order_by_desc_expression | order_by_asc_expression) ~ ("," ~ (order_by_desc_expression | order_by_asc_expression))* }
order_by_asc_expression  = { expression ~ ("ASCENDING" | "ASC")? }
order_by_desc_expression = { expression ~ ("DESCENDING" | "DESC") }
skip                     = { skip_kw ~ expression }
modifiers                = {
    (limit ~ ((order_by ~ skip?) | (skip? ~ order_by?)))
  | (order_by ~ ((limit ~ skip?) | (skip? ~ limit?)))
  | (skip ~ ((order_by ~ limit?) | (limit? ~ order_by?)))
}

where_modifier = { "WHERE" ~ expression }

// Statements
statement = {
    create_statement
  | optional_match_statement
  | match_statement
  | return_statement
  | call_statement
  | with_statement
  | unwind_statement
  | delete_statement
  | detach_delete_statement
  | set_statement
  | remove_statement
}

star = { "*" }

create_statement         = { "CREATE" ~ node_or_edge_pattern ~ ("," ~ node_or_edge_pattern)* }
match_statement          = { "MATCH" ~ node_or_edge_or_path_pattern ~ ("," ~ node_or_edge_or_path_pattern)* ~ where_modifier? }
optional_match_statement = { "OPTIONAL" ~ match_statement }
return_statement         = { "RETURN" ~ (star | named_expression) ~ ("," ~ named_expression)* ~ modifiers? }
call_statement           = { "CALL" ~ function_name ~ "()" }
with_statement           = { "WITH" ~ (star | named_expression) ~ ("," ~ named_expression)* ~ modifiers? }
unwind_statement         = { "UNWIND" ~ named_expression }
delete_statement         = { "DELETE" ~ expression ~ ("," ~ expression)* }
detach_delete_statement  = { "DETACH" ~ "DELETE" ~ expression ~ ("," ~ expression)* }
set_statement            = { "SET" ~ set_expression ~ ("," ~ set_expression)* }
remove_statement         = { "REMOVE" ~ remove_expression ~ ("," ~ remove_expression)* }

// literals
int            = @{ ("+" | "-")? ~ ('0'..'9')+ }
null_lit       =  { "null" }
true_lit       =  { "true" }
false_lit      =  { "false" }
num            = @{ int ~ "." ~ ASCII_DIGIT* ~ (^"e" ~ int)? }
string_literal = ${ "'" ~ inner ~ "'" }
inner          = @{ char* }
function_name  =  { ident ~ ("." ~ ident)* }

// Expression

set_expression       = _{ set_eq_expression | set_add_expression | set_label_expression }
set_eq_expression    =  { set_eq_member_access ~ "=" ~ expression }
set_add_expression   =  { set_eq_member_access ~ "+=" ~ expression }
remove_expression    = _{ remove_member_access | set_label_expression }
set_label_expression =  { ident ~ (":" ~ ident)+ }
set_eq_member_access =  { (("(" ~ ident ~ ")") | ident) ~ ("." ~ ident)* }
remove_member_access =  { (("(" ~ ident ~ ")") | ident) ~ ("." ~ ident)+ }

expression = { prefix? ~ expression_term ~ postfix? ~ (infix ~ prefix? ~ expression_term ~ postfix?)* }

infix   = _{ addition | substraction | multiplication | division | modulo | or | and | equal | different | in_ | not_in | superior | inferior | superior_equal | inferior_equal }
postfix = _{ is_null | is_not_null }
prefix  = _{ negation | not }

addition       = { "+" }
substraction   = { "-" }
multiplication = { "*" }
division       = { "/" }
modulo         = { "%" }

or_kw          = @{ "OR" ~ !ASCII_ALPHA }
or             =  { or_kw }
and_kw         = @{ "AND" ~ !ASCII_ALPHA }
and            =  { and_kw }
equal          =  { "=" }
different      =  { "<>" }
inferior       =  { "<" }
superior       =  { ">" }
inferior_equal =  { "<=" }
superior_equal =  { ">=" }
not_in         =  { "NOT" ~ "IN" }
in_            =  { "IN" }

negation = { "-" }
not      = { "NOT" }

is_null     = { "IS" ~ "NULL" }
is_not_null = { "IS" ~ "NOT" ~ "NULL" }

label_check_expression = { ident ~ (":" ~ ident)+ }

parenthesised_expression = { "(" ~ expression ~ ")" }
named_expression         = { (expression ~ "AS" ~ ident) | expression }
function_call            = { function_name ~ "(" ~ expression ~ ("," ~ expression)* ~ ")" }
count_star               = { "count" ~ "(" ~ "*" ~ ")" }
expression_term          = { null_lit | true_lit | false_lit | num | int | string_literal | map | array | member_access | label_check_expression | parameter | parenthesised_expression | function_call | count_star | ident }

parameter     = { "$" ~ parameter_name }
member_access = { ident ~ ("." ~ ident)+ }

pair = { ident ~ ":" ~ expression }

array = {
    "[" ~ "]"
  | "[" ~ expression ~ ("," ~ expression)* ~ "]"
}

map = {
    "{" ~ "}"
  | "{" ~ pair ~ ("," ~ pair)* ~ "}"
}

// label_expression

label_expression = _{ label_inclusion }

label_inclusion   = { label_alternative ~ (":" ~ label_expression)* }
label_alternative = { label_atom ~ ("|" ~ label_expression)* }
label_atom        = { label_group | ":"? ~ ident }
label_group       = { "(" ~ label_expression ~ ")" }
