WHITESPACE = _{ " " | "\t" | "\n" }
ident = @{ ASCII_ALPHA ~ (ASCII_ALPHANUMERIC | "_")* ~ "'"* }
char = {
    !("'" | "\\") ~ ANY
    | "\\" ~ ("\"" | "\\" | "/" | "b" | "f" | "n" | "r" | "t")
    | "\\" ~ ("u" ~ ASCII_HEX_DIGIT{4})
}

// Query
query = _{ SOI ~ statement* ~ ";"? ~ EOI }

// fragments

labels = { (":" ~ ident)* }
pattern = { ident? ~ labels ~ map? }
node_pattern = { "(" ~ pattern ~ ")" }
edge_pattern = { "(" ~ pattern ~ ")-[" ~ pattern ~ "]->(" ~ pattern ~ ")" }
reverse_edge_pattern = { "(" ~ pattern ~ ")<-[" ~ pattern ~ "]-(" ~ pattern ~ ")" }
undirected_edge_pattern = { ( "(" ~ pattern ~ ")-[" ~ pattern ~ "]-(" ~ pattern ~ ")" ) | ( "(" ~ pattern ~ ")<-[" ~ pattern ~ "]->(" ~ pattern ~ ")" ) }
node_or_edge_pattern = _{ edge_pattern | reverse_edge_pattern | undirected_edge_pattern | node_pattern  }

// Statements
statement = { create_statement | match_statement | return_statement | call_statement | with_statement | unwind_statement }

star = { "*" }

create_statement = { "CREATE" ~ node_or_edge_pattern ~ ( "," ~ node_or_edge_pattern )* }
match_statement = { "MATCH" ~ node_or_edge_pattern ~ ( "," ~ node_or_edge_pattern )* }
return_statement = { "RETURN" ~ named_expression ~ ("," ~ named_expression )* }
call_statement = { "CALL" ~ function_name ~ "()" }
with_statement = { "WITH" ~ (star | named_expression) ~ ("," ~ named_expression )* }
unwind_statement = { "UNWIND" ~ named_expression }

// literals
int = { ("+" | "-")? ~ ASCII_DIGIT+ }
null_lit = { "null" }
true_lit = { "true" }
false_lit = { "false" }
num = { int ~ ("." ~ ASCII_DIGIT*)? ~ (^"e" ~ int)? }
string_literal = ${ "'" ~ inner ~ "'" }
inner = @{ char* }
function_name = { ident ~ ("." ~ ident)* }

// Expression

named_expression = { expression ~ "AS" ~ ident | expression }
expression = _{ null_lit | true_lit | false_lit | num | string_literal | map | array | member_access | ident | parameter }

parameter = { "$" ~ ident }
member_access = { ident ~ ("." ~ ident)+}

pair = { ident ~ ":" ~ expression }

array = {
   "[" ~ "]" |
   "[" ~ expression ~ ("," ~ expression)* ~ "]"
  }

map = {
  "{" ~ "}" |
  "{" ~ pair ~ ("," ~ pair)* ~ "}"
}