WHITESPACE    = _{ " " | "\t" | "\n" }
ident         = @{ ASCII_ALPHA ~ (ASCII_ALPHANUMERIC | "_")* ~ "'"* }
char          =  {
    !("'" | "\\") ~ ANY
  | "\\" ~ ("\"" | "\\" | "/" | "b" | "f" | "n" | "r" | "t")
  | "\\" ~ ("u" ~ ASCII_HEX_DIGIT{4})
}
nothing_ident = @{ "###"+ }

// Query
query = _{ SOI ~ statement* ~ ";"? ~ EOI }

nothing = { nothing_ident? }

// fragments

labels       = { ":" ~ label_expression }
pattern      = { ident? ~ labels? ~ map? }
node_pattern = { "(" ~ pattern ~ ")" }

directed_edge_pattern   = { (")-[" ~ pattern ~ "]->(") | (nothing ~ ")-->(") }
reversed_edge_pattern   = { (")<-[" ~ pattern ~ "]-(") | (nothing ~ ")<--(") }
undirected_edge_pattern = { (")-[" ~ pattern ~ "]-(") | (")<-[" ~ pattern ~ "]->(") | (nothing ~ ")--(") }
edge_pattern            = { "(" ~ pattern ~ ((directed_edge_pattern | reversed_edge_pattern | undirected_edge_pattern) ~ pattern)+ ~ ")" }

path_pattern = { ident ~ "=" ~ "(" ~ pattern ~ (directed_edge_pattern | reversed_edge_pattern | undirected_edge_pattern) ~ pattern ~ ")" }

node_or_edge_pattern         = _{ edge_pattern | node_pattern }
node_or_edge_or_path_pattern = _{ edge_pattern | node_pattern | path_pattern }

// Modifiers

limit          = { "LIMIT" ~ expression }
modifiers      = { limit }
where_modifier = { "WHERE" ~ expression }

// Statements
statement = { create_statement | optional_match_statement | match_statement | return_statement | call_statement | with_statement | unwind_statement }

star = { "*" }

create_statement         = { "CREATE" ~ node_or_edge_pattern ~ ("," ~ node_or_edge_pattern)* }
match_statement          = { "MATCH" ~ node_or_edge_or_path_pattern ~ ("," ~ node_or_edge_or_path_pattern)* ~ where_modifier? }
optional_match_statement = { "OPTIONAL" ~ match_statement }
return_statement         = { "RETURN" ~ named_expression ~ ("," ~ named_expression)* }
call_statement           = { "CALL" ~ function_name ~ "()" }
with_statement           = { "WITH" ~ (star | named_expression) ~ ("," ~ named_expression)* ~ modifiers? }
unwind_statement         = { "UNWIND" ~ named_expression }

// literals
int            = @{ ("+" | "-")? ~ ('0'..'9')+ }
null_lit       =  { "null" }
true_lit       =  { "true" }
false_lit      =  { "false" }
num            = @{ int ~ "." ~ ASCII_DIGIT* ~ (^"e" ~ int)? }
string_literal = ${ "'" ~ inner ~ "'" }
inner          = @{ char* }
function_name  =  { ident ~ ("." ~ ident)* }

// Expression

expression = { different_bin_op_expression }

different_bin_op_expression = { in_bin_op_expression ~ ("<>" ~ expression)? }
in_bin_op_expression        = { is_null_expression_or_term ~ ("IN" ~ expression)? }

is_null_expression         = { expression_term ~ "IS" ~ "NULL" }
is_null_expression_or_term = { is_null_expression | expression_term }

not_expression         = { "NOT" ~ expression_term }
label_check_expression = { ident ~ (":" ~ ident)+ }

parenthesised_expression = { "(" ~ expression ~ ")" }
named_expression         = { (expression ~ "AS" ~ ident) | expression }
function_call            = { function_name ~ "(" ~ expression ~ ("," ~ expression)* ~ ")" }
count_star               = { "count" ~ "(" ~ "*" ~ ")" }
expression_term          = { null_lit | true_lit | false_lit | num | int | string_literal | map | array | member_access | label_check_expression | parameter | parenthesised_expression | not_expression | function_call | count_star | ident }

parameter     = { "$" ~ ident }
member_access = { ident ~ ("." ~ ident)+ }

pair = { ident ~ ":" ~ expression }

array = {
    "[" ~ "]"
  | "[" ~ expression ~ ("," ~ expression)* ~ "]"
}

map = {
    "{" ~ "}"
  | "{" ~ pair ~ ("," ~ pair)* ~ "}"
}

// label_expression

label_expression = _{ label_inclusion }

label_inclusion   = { label_alternative ~ (":" ~ label_expression)* }
label_alternative = { label_atom ~ ("|" ~ label_expression)* }
label_atom        = { label_group | ":"? ~ ident }
label_group       = { "(" ~ label_expression ~ ")" }
