[package]
name = "gqliterune"
description = "GQLite bindings for the Rune programming language."
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
readme = "README.MD"

[features]
default = ["gqb"]
gqb = ["dep:gqb"]

[dependencies]
gqlitedb = { workspace = true }
gqb = { workspace = true, optional = true }
graphcore = { workspace = true }

ccutils = { workspace = true }
rune = { workspace = true }

[dev-dependencies]
ccutils = { workspace = true, features = ["rune", "testing"] }
