require 'rake'
require 'fileutils'

# extconf
require "rake/extensiontask"

# Gem
require 'rubygems'
require 'rubygems/package_task'



# Gemspec

GEMSPEC = Gem::Specification.new do |s|
  s.name = "gqlite"
  s.version = "1.2.0"
  s.summary = "Ruby bindings for GQLite, a Graph Query library."
  s.description = <<-DESC
GQLite is a Rust-language library, with a C interface, that implements a small, fast, self-contained, high-reliability, full-featured, Graph Query database engine.
GQLite support multiple database backends, such as SQLite and redb.
This enable to achieve high performance and for application to combine Graph queries with traditional SQL queries.

GQLite source code is license under the [MIT License](LICENSE) and is free to everyone to use for any purpose. 

The official repositories contains bindings/APIs for C, C++, Python, Ruby and Crystal.

The library is still in its early stage, but it is now fully functional. Development effort has now slowed down and new features are added on a by-need basis. It supports a subset of OpenCypher, with some ISO GQL extensions.
  
Example of use
--------------

```ruby
require 'gqlite'

begin
  # Create a database on the file "test.db"
  connection = GQLite::Connection.new filename: "test.db"

  # Execute a simple query to create a node and return all the nodes
  value = connection.execute_oc_query("CREATE () MATCH (n) RETURN n")

  # Print the result
  if value.nil?
    puts "Empty results"
  else
    puts "Results are \#{value.to_s}"
  end
rescue GQLite::Error => ex
  # Report any error
  puts "An error has occured: \#{ex.message}"
end

```

The documentation for the GQL query language can found in [OpenCypher](https://auksys.org/documentation/5/libraries/gqlite/opencypher/) and for the [API](https://auksys.org/documentation/5/libraries/gqlite/api/).

DESC
  s.authors     = ["Cyrille Berger"]
  s.homepage    = "https://gitlab.com/auksys/gqlite"
  s.license     = "MIT"
  
  s.files = Dir[
    "lib/**/*.rb",
    "ext/**/.cargo/config.toml",
    "ext/**/*.{rs,toml,lock,rb,pest,sql}"
  ]
  s.require_paths = ["lib"]  
  s.extensions = %w[ext/gqliterb/extconf.rb]

  # needed until rubygems supports Rust support is out of beta
  s.add_dependency "rb_sys", "~> 0.9.39"

  # only needed when developing or packaging your gem
  s.add_development_dependency "rake-compiler", "~> 1.2.0"
end

# Tasks

Rake::ExtensionTask.new "gqliterb" do |ext|
  ext.ext_dir = 'ext/gqliterb'
  ext.lib_dir = 'lib/gqliterb'
  ext.name    = 'gqliterb'
end

Gem::PackageTask.new(GEMSPEC) do |pkg|
end

task :gem => 'check_ext'

desc "Check for ext directory"
task :check_ext do |t|
  unless Dir.exist?('ext')
    abort "❌ ERROR: 'ext' directory not found. Run 'rake prepare:ext' first."
  end
end

namespace :prepare do
  desc "Package the ext directory with gqliterb"
  task :ext do |t|

    tmp_dir = "tmp/"
    ext_dir = "ext"
    gqliterb_dir = File.join(ext_dir, "gqliterb")
    gqliterb_dot_cargo_dir = File.join(gqliterb_dir, ".cargo")
    gqlitedb_dir = File.join(gqliterb_dir, "vendor/gqlitedb")
    extconf_source = "extconf.rb"
    config_toml_source = "config.toml"


    puts "🧹 Cleaning directories"
    FileUtils.rm_rf(tmp_dir)
    FileUtils.mkdir_p(tmp_dir)
    FileUtils.rm_rf(ext_dir)
    FileUtils.mkdir_p(gqliterb_dir)
    FileUtils.mkdir_p(gqlitedb_dir)

    # Helper function to package and find crate
    def export_crate(crate_name, tmp_dir, dst_dir)
      puts "📦 Packaging '#{crate_name}' crate..."
      system("cargo", "package", "--package", crate_name, "--target-dir=#{tmp_dir}", "--allow-dirty", "--no-verify") or
        raise "❌ Failed to package #{crate_name}"
      crate_path = Dir[File.join(tmp_dir, "package", "#{crate_name}-*.crate")].first
      raise "❌ Could not find packaged crate for #{crate_name}" unless crate_path

      puts "📦 Unpacking #{crate_path} to #{dst_dir}"
      system("tar", "-xzf", crate_path, "--strip-components=1", "-C", dst_dir) or
        raise "❌ Failed to unpack #{crate_path}"

      puts "🧼 Removing .crate archive"
      FileUtils.rm_f(crate_path)
    
      puts "✅ Done: #{crate_name} crate unpacked to #{dst_dir}"
    end

    export_crate("gqliterb", tmp_dir, gqliterb_dir)
    export_crate("gqlitedb", tmp_dir, gqlitedb_dir)

    puts "📄 Copying extconf.rb"
    FileUtils.cp(extconf_source, gqliterb_dir)

    puts "📄 Copying config.toml"
    FileUtils.mkdir_p(gqliterb_dot_cargo_dir)
    FileUtils.cp(config_toml_source, gqliterb_dot_cargo_dir)

    puts "🧹 Cleaning temporary directory"
    FileUtils.rm_rf(tmp_dir)

    puts "✅ Done: preparing `gqliterb`"
  end
end


task :clean do
  desc "Clean artefacts"
  FileUtils.rm_rf("tmp/")
  FileUtils.rm_rf("ext/")
  FileUtils.rm_rf("pkg/")
end
