[package]
name = "gqb"
version = "0.1.0"
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
graphcore = { workspace = true }

askama = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
gqlitedb = { workspace = true }
