[package]
name = "gqlitebrowser"
description = "GUI Browser for GQLite databases."
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
readme = "README.MD"

[package.metadata.docs.rs]
all-features = true
targets = ["x86_64-unknown-linux-gnu", "wasm32-unknown-unknown"]

[dependencies]
brisk-eframe = { version = "0.6", features = ["rfd", "table"] }
brisk-egui = { version = "0.6" }
ccutils = { workspace = true, features = ["serde", "sync"] }
egui = "0.33"
egui_table = "0.5"
eframe = { version = "0.33", default-features = false, features = [
    "accesskit",     # Make egui compatible with screen readers. NOTE: adds a lot of dependencies.
    "default_fonts", # Embed the default egui fonts.
    "glow",          # Use the glow rendering backend. Alternative: "wgpu".
    "persistence",   # Enable restoring app state when restarting the app.
    "wayland",       # To support Linux (and CI)
    "x11",           # To support older Linux distributions (restores one of the default features)
] }
log = "0.4"
rfd = "0.15"

# You only need serde if you want app persistence:
serde = { version = "1", features = ["derive"] }
egui_material_icons = "0.5"

# native:
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
env_logger = "0.11"
gqlitedb = { workspace = true }

# web:
[target.'cfg(target_arch = "wasm32")'.dependencies]
gqlitedb = { workspace = true, default-features = false, features = ["redb"] }
wasm-bindgen-futures = "0.4"
web-sys = "0.3"                                                                # to access the DOM (to hide the loading text)
getrandom = { version = "0.3", features = ["wasm_js"] }
